### PR TITLE
Member profile view

### LINKED ISSUE #337: Implement member profile view page
# Todos

- [ ] InlineEditableField
- [x] Profile View (with section permission)
- [ ] Profile inline edit
- [x] MemberStatus component

### PR DESCRIPTION
**Pull request by duongdev**
I've added member profile view functionalities. This PR contains:

- View member profile (all avalable, empty info will be hidden). Other section (work contract, salary) will be added later.
- Permission validation to update member profile (on "Update profile" button).
- Inline profile update will be added later.

Resolves #337

### CODE REVIEW

**Comment by lamvh** [comment]
UI is broken when the input is too long !
@duongdev 

image

**Comment by duongdev** [comment]
@lamvh nice catch! thanks

**Comment by nguyenthienthanh** [comment]
image
@duongdev Layout crash when display name so long.

**Comment by nguyenthienthanh** [comment]
image
@duongdev Date of issue should accept today.

**Comment by QiuJey** [comment]
Header of Profile should be like this, thanks for @nguyenthienthanh take an attention on status
image

update back, edit and log button.

**Comment by lamvh** [comment]
> View member profile (all available, empty info will be hidden). Other section (work contract, salary) will be added later.

All fields are required, I can't check this feature.

**Comment by nguyenthienthanh** [comment]
image
@duongdev An normal member can update other member profile.
## Reproduce:
- Login normal member account
- Copy member access token.
- Use **Insomnia**, **Postman** or other REST client you have, paste copied **access token** into header like the image above.
- Set **x-member-id** with value is id of other member account who is you want to update.
- Use this mutation and data to update the member profile.
```
mutation UpdateMember($input: UpdateMemberInput) {
  member: updateMember(input: $input) {
    id
    account {
      id
      email
      __typename
    }
    __typename
  }
}
```
- Use this data and replace `id` to **id of user who you want to update**
```
{
	"input": {
		"id": user id you want to update,
		"username": "thanhnguyen1",
		"profile": {
			"displayName": "123 12234 2343",
			"dateOfBirth": "2019-05-05T00:00:00.000Z",
			"phone": "123123123",
			"workEmail": "thanhnguyen+1@targeek.io",
			"address": {
				"address": "123123123123",
				"ward": "123",
				"district": "123",
				"city": "123",
				"country": "Việt Nam",
				"__typename": "MemberAddress"
			},
			"identification": {
				"number": "1231123123",
				"issueDate": "2019-05-05T00:00:00.000Z",
				"issuePlace": "123123",
				"__typename": "MemberIdentification"
			},
			"__typename": "MemberProfile"
		}
	}
}
```

**Comment by duongdev** [comment]
Handled loooongTextWithoutSpaces
image

image

image

**Comment by duongdev** [comment]
@nguyenthienthanh your major security bug has been fixed. Please wait for the new pushes deployed and test again. Thanks.

**Comment by duongdev** [comment]
Updated with

- member's status chip repositioned.
- member's id issue date accepts today.

image

**Pull request merged**
